### ISSUE TITLE
PHP fatal error

### ISSUE THREAD

**Issue by marlara** [pkp/customHeader#24] opened 2022-07-11 14:15 UTC
I get this error with PHP 8.1 and OJS 3.3.0.11

`[php:error] [pid 2434172] [client 37.103.18.12:40340] PHP Fatal error:  Declaration of CustomHeaderSettingsForm::execute($request, ...$functionArgs) must be compatible with Form::execute(...$functionArgs) in /var/www/ojs/plugins/generic/customHeader/CustomHeaderSettingsForm.inc.php on line 71, referer: https://aldrovandiana.it/management/settings/website`

**Comment by marlara** [comment] 2022-07-14 14:48
Hi, sorry to bother, but this is a bit of a critic issue for me, because without the customHeader plugin i don't know how to set the cookie bar

**Comment by asmecher** [comment] 2022-07-14 18:41
This is a duplicate of https://github.com/pkp/customHeader/issues/21 -- see details there.

**Comment by marlara** [comment] 2022-07-14 18:59
Thank you very much asmecher, and sorry for the duplicate!
Works well

**Closed as completed** 2023-01-27 17:58 UTC
